### ISSUE TITLE
'Restore' is not working, it shows error saying "Backup file <backup-XX>.json doesn't exist!" (Its working fine if we pass the parameters)

### ISSUE THREAD

**Issue by nirav-appveen** [appveen/datastack-backup-restore#1]
'Restore' is not working, it shows error saying "Backup file <backup-XX>.json doesn't exist!". 

![1) Restore showing error](https://user-images.githubusercontent.com/96046386/177105566-48568eb2-c8e7-479d-b014-de1e94916240.jpg)

*Its working fine if we pass the parameters.

![Working fine if we pass parameters](https://user-images.githubusercontent.com/96046386/177105582-3f417391-11c0-4dfe-8224-1556266a05b9.jpg)

**Comment by jerrymannel** [comment]
This is working as expected.
To restore, you need to pass the backup file from where the configurations must be read and restored.
`-b` flag is used to pass the backup file.
